config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'devise/invitations', sessions: 'user/session', registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  get 'admin/users/list', to: 'admin/users#list'
  namespace :admin do
    resources :users
    resources :categories
    resources :products
    resources :orders, only: [:index]
  end

  resources :users, only: [:edit, :show] do
    collection do
      patch 'update_password'
    end
  end

  resources :order_items
  resource :cards, only: [:show, :update]
  resources :products, only: [:index, :show]
  resource :orders, only: [:update]
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_category
  has_one_attached :product_image
  has_many :order_items

  scope :published, -> { where("status = 'publish'") }

  STATUS = %w( publish draft pending ).freeze
  validates :status, presence: true, inclusion: { in: STATUS }
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, except: [:index, :new, :create]
  before_action :set_categories, only: [:edit, :new]

  def index
    @products= Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'Product Created!'
    else
      flash[:error] = 'Failed to create Product!'
    end
    redirect_to admin_products_path
  end

  def show; end

  def edit; end

  def update
    if @product.update(product_params)
      flash[:notice] = 'Product updated!'
      redirect_to admin_products_path
    else
      flash[:error] = 'Failed to edit Product!'
      render "edit"
    end
  end

  def destroy
    if @product.destroy
      flash[:notice] = "Product deleted successfully"
    else
      flash[:error] = 'Failed to delete Product!'
    end
    redirect_to admin_products_path
  end

  private

  def product_params
    params.require(:product).permit(:title, :price, :description, :status, :product_category_id, :product_image)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def set_categories
    @categories = ProductCategory.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products= Product.published
    @order_item = current_order.order_items.new
  end
  def show
    @product= Product.find(params[:id])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def categories_title(categories)
    categories.pluck(:title)
  end
end

app/views/admin/products/edit.html.erb
<div class='container float-right'>
  <div class='row align-items-center'>
    <div class='col-5'>
      <h2>Edit Product</h2>

      <%= form_for(@product, url:{action: "update"}) do |form| %>
        <div class="field">
          <%= form.label :title %>
          <%= form.text_field :title, class: 'form-control' %>
        </div>
        <div class="field">
          <p> Value </p>
          <%= form.text_field :price, class: 'form-control' %>
        </div>
        <div class="field">
          <%= form.label :description %>
          <%= form.text_field :description, class: 'form-control' %>
        </div>
        <div class="field">
          <p> Status </p>
          <%= form.select :status, options_for_select(Product::STATUS), class: 'form-control' %>
        </div>
        <div class="field">
          <p> Category </p>
          <%= form.select :product_category_id, options_for_select(@categories.pluck(:title, :id)), class: 'form-control' %>
        </div>
        <div class="actions mt-3">
          <p><%= form.submit "Update", class: 'btn btn-primary'%></p>
        </div>
      <% end %>

      <%= link_to "Back", :back, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="jumbotron text-center">
  <h1>Products</h1>
  <%= link_to 'Add New Product', new_admin_product_path %>
</div>

<div class="page-content page-container" id="page-content">
  <div class="d-flex justify-content-center">
    <div class="card user-card-full">
      <table class="table">
        <thead>
          <tr>
            <th> ID </th>
            <th> Name </th>
            <th> Value </th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td> <%= product.id %> </td>
              <td> <%= product.title %> </td>
              <td> <%= number_to_currency(product.price) %> </td>
              <td> <%= link_to 'Show', admin_product_path(product) %> </td>
              <td> <%= link_to 'Edit', edit_admin_product_path(product) %> </td>
              <td> <%= link_to "Delete", admin_product_path(product), data: { swal_msg: 'Are you sure you wish to delete this entity?' }, method: :delete, class: 'swal' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class= "jumbotron text-center">
  <h2>New Product</h2>
</div>

<div class="page-content page-container" id="page-content">
  <div class="d-flex justify-content-center">
    <div class="card user-card-full">
      <div class="row-xs-9">
        <%= form_for [:admin, @product] do |form| %>
          <div class="col-xs-9">
            <p>Title</p>
            <%= form.text_field :title, class: 'form-control'%>
          </div>
          <div class="col-xs-9">
            <p>Price</p>
            <%= form.text_field :price, class: 'form-control'%>
          </div>
          <div class="col-xs-9">
            <p>Description</p>
            <%= form.text_field :description, class: 'form-control'%>
          </div>
          <div class="col-xs-9">
            <p>Status</p>
            <%= form.select :status, options_for_select(Product::STATUS), class: 'form-control'%>
          </div>
          <div class="col-xs-9">
            <p>Categories</p>
            <%= form.select :product_category_id, options_for_select(@categories.pluck(:title, :id)), class: 'form-control'%>
          </div>
          <div class="col-xs-9">
            <p>Image</p>
            <%= form.file_field :product_image, class: 'form-control'%>
          </div>
          <div class="actions mt-3">
            <%= link_to "BACK", :back, class: 'btn btn-primary' %>
            <%= form.submit "ADD PRODUCT", class: 'btn btn-primary'%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="jumbotron text-center">
  <h1>Product Details</h1>
  <%= link_to 'Back to List', admin_products_path %>
</div>
<div class="page-content page-container" id="page-content">
  <div class="d-flex justify-content-center">
    <div class="card user-card-full">
      <div class="row">
        <div class="col-sm-8">
          <p class="m-b-10 f-w-600">ID</p>
          <h6 class="text-muted f-w-400"><%= @product.id %></h6>
        </div>
        <div class="col-sm-8">
          <p class="m-b-10 f-w-600">Title</p>
          <h6 class="text-muted f-w-400"><%= @product.title %></h6>
        </div>
        <div class="col-sm-8">
          <p class="m-b-10 f-w-600">Title</p>
          <h6 class="text-muted f-w-400"><%= number_to_currency(@product.price) %></h6>
        </div>
      </div>
    </div>
  </div>
</div>