config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'devise/invitations', sessions: 'user/session', registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  get 'admin/users/list', to: 'admin/users#list'
  namespace :admin do
    resources :users
    resources :categories
    resources :products
    resources :orders, only: [:index]
  end

  resources :users, only: [:edit, :show] do
    collection do
      patch 'update_password'
    end
  end

  resources :order_items
  resource :cards, only: [:show, :update]
  resources :products, only: [:index, :show]
  resource :orders, only: [:update]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders

  validates :full_name, presence: true
  validates :password, format: {with: /(?=.*?[A-Z])(?=(.*[a-z]){1,})(?=(.*[\d]){1,})(?=(.*[\W]){1,})(?!.*\s).{8,}/}
  # Include default devise modules. Others available are:
  # :timeoutable, and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :lockable, :confirmable

  attr_writer :login

  def login
    full_name || email
  end

  def self.search(term)
    if term
      where("lower(full_name) LIKE ? or lower(email) LIKE ? or lower(admin) LIKE ?", "%#{term}%", "%#{term}%", "%#{term}%")
    else
      all
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(full_name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:full_name].nil?
        where(conditions).first
      else
       where(full_name: conditions[:full_name]).first
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, except: [:index, :list]
  helper_method :sort_column, :sort_direction

  def index
    @users= User.all
    respond_to do |format|
      format.csv do
        headers['Content-Disposition'] = 'attachment; filename="ems-users-list.csv"'
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'User updated!'
      redirect_to admin_users_list_path
    else
      flash[:error] = 'Failed to edit User!'
      render "edit"
    end
  end

  def list
    @results= User.search(params[:term]).order(sort_column + " " + sort_direction).page(params[:page]).per(5)
  end

  def destroy
    @user.destroy
    redirect_to admin_users_list_path, notice: "User deleted successfully"
  end

  private

  def user_params
    # NOTE: Using `strong_parameters` gem
    params.require(:user).permit(:full_name, :email, :password, :password_confirmation)
  end

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "full_name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/user/session_controller.rb
class User::SessionController < Devise::SessionsController
  def destroy
    if(current_order.status = false)
      current_order.destroy
    end
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit]

  def show
    render "user/show"
  end

  def edit
    render "user/edit"
  end

  def update_password
    if current_user.update(user_params)
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in(current_user)
      redirect_to root_path
    else
      render "user/edit"
    end
  end

  private

  def user_params
    # NOTE: Using `strong_parameters` gem
    params.require(:user).permit(:password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/admin/users/edit.html.erb
<div class='container float-right'>
  <div class='row align-items-center'>
    <div class='col-5'>
      <h2>My EMS Profile</h2>

      <%= form_with(model: [:admin, @user], local: true) do |form| %>
        <div class="field">
          <%= form.label :full_name %>
          <%= form.text_field :full_name, class: 'form-control'%>
        </div>

        <div class="field">
          <%= form.label :email %>
          <%= form.email_field :email, autofocus: true, autocomplete: 'email', class: 'form-control' %>
        </div>

        <div class="field">
          <%= form.label :password %>
          <%= form.password_field :password, autocomplete: "new-password", class: 'form-control' %>
          <% if @minimum_password_length %>
            <em><%= @minimum_password_length %> characters minimum</em>
          <% end %>
        </div>

        <div class="field">
          <%= form.label :password_confirmation %>
          <%= form.password_field :password_confirmation, autocomplete: "new-password", class: 'form-control' %>
        </div>

        <div class="actions mt-3">
          <p><%= form.submit "Update", class: 'btn btn-primary'%></p>
        </div>
      <% end %>

      <%= link_to "Back", :back, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/admin/users/index.csv.erb
<% headers = ['Full Name', 'Email', 'Admin Status'] %>
<%= CSV.generate_line headers %>
<% @users.each do |user| %>
  <%= CSV.generate_line([user.full_name, user.email, user.admin]) %>
<% end %>

app/views/admin/users/list.html.erb
<div class="jumbotron text-center">
  <h1>Users List</h1>
  <%= link_to 'Invite User', new_user_invitation_path %>
</div>

<div class="page-content page-container" id="page-content">
  <div class="d-flex justify-content-center">
    <div class="card user-card-full">
      <table class="table">
        <%= form_with method: :get, local: true do |form| %>
          <div class="input-group justify-content-center">
            <div class="input-group-btn">
              <%= form.submit 'Search USERS', class:'btn btn-success'%>
            </div>
            <%= form.text_field :term,value: params[:term] %>
            <div class="input-group-btn">
              <%= link_to 'Download CSV', admin_users_path(format: :csv), class: 'btn btn-success'%>
            </div>
          </div>
        <% end %>
        <thead>
          <tr>
            <th><%= sortable "full_name" %></th>
            <th><%= sortable "email" %></th>
            <th><%= sortable "admin" %></th>
          </tr>
        </thead>
        <tbody>
          <% @results.each do |user| %>
            <tr>
              <td> <%= user.full_name %> </td>
              <td> <%= user.email %> </td>
              <td> <%= user.admin %> </td>
              <td> <%= link_to 'Show', admin_user_path(user) %> </td>
              <td> <%= link_to 'Edit', edit_admin_user_path(user) %> </td>
              <td> <%= link_to "Delete", admin_user_path(user), data: { confirm: "Are you sure?" }, method: :delete %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center">
  <%= paginate @results %>
</div>

app/views/admin/users/show.html.erb
<div class="jumbotron text-center">
  <h1>My Profile</h1>
  <p><%= link_to "Back to List", admin_users_list_path %></p>
</div>
<div class="page-content page-container" id="page-content">
  <div class="d-flex justify-content-center">
    <div class="card user-card-full">
      <div class="row">
        <div class="col-sm-8">
          <p class="m-b-10 f-w-600">Full Name</p>
          <h6 class="text-muted f-w-400"><%= @user.full_name %></h6>
        </div>
        <div class="col-sm-8">
          <p class="m-b-10 f-w-600">Email</p>
          <h6 class="text-muted f-w-400"><%= @user.email %></h6>
        </div>
        <div class="col-sm-8">
          <p class="m-b-10 f-w-600">Admin Status</p>
          <h6 class="text-muted f-w-400"><%= @user.admin %></h6>
        </div>
      </div>
    </div>
  </div>
</div>