config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'devise/invitations', sessions: 'user/session', registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  get 'admin/users/list', to: 'admin/users#list'
  namespace :admin do
    resources :users
    resources :categories
    resources :products
    resources :orders, only: [:index]
  end

  resources :users, only: [:edit, :show] do
    collection do
      patch 'update_password'
    end
  end

  resources :order_items
  resource :cards, only: [:show, :update]
  resources :products, only: [:index, :show]
  resource :orders, only: [:update]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EMS</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">EMS</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-supported-content" aria-controls="navbar-supported-content" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar-supported-content">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link">
              <%= link_to "Home", root_path %>
            </a>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link">
                <%= link_to "My Profile", user_path(current_user) %>
              </a>
            </li>
            <% if !(current_user.admin?) %>
            <li class="nav-item">
              <a class="nav-link">
                <%= link_to "Products", products_path %>
              </a>
            </li>
            <% end %>
            <% if current_user.admin? %>
              <li class="nav-item">
                <a class="nav-link">
                 <%= link_to "List Users", admin_users_list_path %>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link">
                  <%= link_to "List Categories", admin_categories_path %>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link">
                  <%= link_to "List Products", admin_products_path %>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link">
                  <%= link_to "List Orders", admin_orders_path %>
                </a>
              </li>
            <% end %>
            <li class="nav-item">
              <a class="nav-link">
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
              </a>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link">
                <%= link_to "Sign In", new_user_session_path %>
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>

</html>